In [1]:
import sys
sys.path.append("../") # go to parent dir

from main.fermionic import *

#basis, vacio = integer_digits(n)
%load_ext autoreload
%autoreload 2

# Operators

We then create an instance of the class Operator, with dimension n. 
This class contains the operators with the corresponding name in the program are

$c_i \rightarrow cm(i)\\
c_i^{\dagger} \rightarrow cd(i)\\
c_ic_j \rightarrow cmcm(i,j)\\
c_i^{\dagger}c_j^\dagger \rightarrow cdcd(i,j)\\
c_ic_j^\dagger \rightarrow cmcd(i,j)\\
c_i^\dagger c_j \rightarrow cdcm(i)$

One of the great advantages of defining these operators as elements of a class, is that it is possible to simultaneously define operators for different dimensions. This can be useful for a number of application, for example for comparing results in different dimensions without re-running the core program each time you switch dimension.

You can do, for instance

op4 = Operator(4)

op6 = Operator(6)

In [2]:
# n is the dimension of the system
n = int(input('Choose dimension: '))

op = Operator(n)

Choose dimension: 4


Optionally, you can look at the elements of the basis in which the operators are written. 


In [3]:
op.basis()

matrix([[0, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 0, 1, 1],
        [0, 1, 0, 0],
        [0, 1, 0, 1],
        [0, 1, 1, 0],
        [0, 1, 1, 1],
        [1, 0, 0, 0],
        [1, 0, 0, 1],
        [1, 0, 1, 0],
        [1, 0, 1, 1],
        [1, 1, 0, 0],
        [1, 1, 0, 1],
        [1, 1, 1, 0],
        [1, 1, 1, 1]], dtype=int32)

Now, we can acces the operators belonging to each mode. 

In [4]:
op.cm(0) #destruction operator for mode 0 (remember the first element is always 0 in python)

<16x16 sparse matrix of type '<class 'numpy.intc'>'
	with 8 stored elements in Compressed Sparse Row format>

Program runs with sparse matrices, because it is much faster for matrix operations. In order to visualize the operatos as a regular matrix, you can use .todense() method.

In [5]:
op.cm(0).todense()

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [6]:
op.cd(2).todense() #This is the creation operator for the third mode

matrix([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  

In [7]:
op.cdcm(1,2).todense() #This is the operator cd(1).cm(2). 

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [8]:
#When both arguments are equal, this is the number operator (counting ocupation of the i mode)
op.cdcm(2,2).todense()

matrix([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int32)

# States

States are vectors that indicate the coefficient for each element in basis. In this program the **must** be numpy arrays in order to work. Let's refresh the shape of basis:

In [9]:
op.basis()

matrix([[0, 0, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 1, 0],
        [0, 0, 1, 1],
        [0, 1, 0, 0],
        [0, 1, 0, 1],
        [0, 1, 1, 0],
        [0, 1, 1, 1],
        [1, 0, 0, 0],
        [1, 0, 0, 1],
        [1, 0, 1, 0],
        [1, 0, 1, 1],
        [1, 1, 0, 0],
        [1, 1, 0, 1],
        [1, 1, 1, 0],
        [1, 1, 1, 1]], dtype=int32)

The first elemnt of basis is the vacuum, and can be accessed through the corresponding method

In [10]:
op.vacuum()

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Basis has $2^n$ elements. Then a state of the shape 
state = [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0] corresponds to occupying the only the third mode

In [11]:
cd2 = op.cd(2)
vacuum = op.vacuum()

cd2.dot(vacuum)

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

We can naturally work with more fermions. For example, let's occupy the first three modes:

In [13]:
cd0 = op.cd(0)
cd1 = op.cd(1)
cd2 = op.cd(2)
vacuum = op.vacuum()

cd0.dot(cd1.dot(cd2.dot(vacuum)))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=int32)

Now we can make more complicated things. For example, we can generate a random state of 2 fermions 

In [20]:
nume = 2
l = len(vacuum)
state = np.zeros(l)
basis = op.basis()

for i in range(l):
    if basis[i].sum() == nume:
        state[i] = 2*np.random.rand()-1
        
print(state)

[ 0.          0.          0.         -0.60946025  0.          0.14192072
 -0.6507898   0.          0.          0.03226491 -0.99098198  0.
  0.93877565  0.          0.          0.        ]


We normalize the state to norm 1. If we forget about this step, the following part will raise an error

In [22]:
state = state/np.sqrt(state.dot(state)) 
print(state)

[ 0.          0.          0.         -0.37232206  0.          0.08670002
 -0.39757048  0.          0.          0.01971078 -0.60539544  0.
  0.57350235  0.          0.          0.        ]


Now we can initialize state as an instance of the class State in order to acces more information about it

In [23]:
ran_state = State(state, op)

We can ask for the one body matrix, which is the matrix with the one body operator contractions, i.e. $\rho^{\rm sp}(i,j) = \langle \psi | c_j^\dagger c_i |\psi\rangle$

In [24]:
ran_state.rhosp()

array([[ 0.6957971 ,  0.24239628,  0.22066885, -0.27512474],
       [ 0.24239628,  0.49448413, -0.37947604, -0.13672008],
       [ 0.22066885, -0.37947604,  0.66318964, -0.04640219],
       [-0.27512474, -0.13672008, -0.04640219,  0.14652913]])

Note: for better understanding, this could also be manually constructed like this

In [31]:
rhosp = np.zeros((n,n))
for i in range(n):
    for j in range(n):
        rhosp[i,j] = state.dot(op.cdcm(j,i).dot(state))
print(rhosp)

[[ 0.6957971   0.24239628  0.22066885 -0.27512474]
 [ 0.24239628  0.49448413 -0.37947604 -0.13672008]
 [ 0.22066885 -0.37947604  0.66318964 -0.04640219]
 [-0.27512474 -0.13672008 -0.04640219  0.14652913]]


The eigenvalues of the one body matrix can be also accessed with the corresponding method

In [28]:
ran_state.eigensp()

array([0.02938251, 0.02938251, 0.97061749, 0.97061749])

And the one body entropy, which is defined as 
$S(\rho^{\rm sp}) = -\sum_i (\lambda_i \log(\lambda_i) + (1-\lambda_i) \log(1-\lambda_i))$
accounting both for particle ($\lambda_i$) and holes ($1-\lambda_i$)

In [30]:
ran_state.ssp()

0.5303563971958811